before_script:
    - git submodule init
    - git submodule update
    - cd ..
    - rm -rf src/gitlab.cs.fau.de/luksen/
    - mkdir -p src/gitlab.cs.fau.de/luksen/
    - cp -r obinex src/gitlab.cs.fau.de/luksen/
    - export GOPATH=$PWD
    - go get golang.org/x/net/websocket
    - go get golang.org/x/sys/unix
    - go get github.com/tylerb/graceful
    - go get github.com/wadey/gocovmerge
    - go install github.com/wadey/gocovmerge
    - cd src/gitlab.cs.fau.de/luksen/obinex

build:
    script:
        - go build gitlab.cs.fau.de/luksen/obinex/...

test:
    script:
        - go test gitlab.cs.fau.de/luksen/obinex/...
        - cd integration_tests
        - run.sh .

coverage:
    script:
        - ./coverage.sh
        - mv coverage_*.html ../../../../obinex/
    artifacts:
        paths:
            - coverage_obinex-server.html
