image: golang

variables:
    GIT_SUBMODULE_STRATEGY: normal

before_script:
    - cd ..
    - rm -rf src/gitlab.cs.fau.de/i4/
    - mkdir -p src/gitlab.cs.fau.de/i4/
    - cp -r obinex src/gitlab.cs.fau.de/i4/
    - export GOPATH=$PWD
    - export PATH=$GOPATH/bin:$PATH
    - go get golang.org/x/net/websocket
    - go get golang.org/x/sys/unix
    - go get golang.org/x/net/http2
    - go get github.com/wadey/gocovmerge
    - go install github.com/wadey/gocovmerge
    - cd src/gitlab.cs.fau.de/i4/obinex

build:
    script:
        - go build gitlab.cs.fau.de/i4/obinex/...

test:
    before_script:
        - apt-get install bats
    script:
        - go test gitlab.cs.fau.de/i4/obinex/obinex
        - go test gitlab.cs.fau.de/i4/obinex/obinex-watcher
        - go test gitlab.cs.fau.de/i4/obinex/obinex-server
        - go test gitlab.cs.fau.de/i4/obinex/obinex-hwmock
        - cd integration_tests
        - ./run.sh

coverage:
    script:
        - ./coverage.sh
        - mv coverage_*.html ../../../../obinex/
    artifacts:
        paths:
            - coverage_obinex-server.html
