image: golang

variables:
    GIT_SUBMODULE_STRATEGY: normal

before_script:
    - cd ..
    - rm -rf src/github.com/maxpeal/
    - mkdir -p src/github.com/maxpeal/
    - cp -r obinex src/github.com/maxpeal/
    - export GOPATH=$PWD
    - export PATH=$GOPATH/bin:$PATH
    - go get golang.org/x/net/websocket
    - go get golang.org/x/sys/unix
    - go get golang.org/x/net/http2
    - go get github.com/wadey/gocovmerge
    - go install github.com/wadey/gocovmerge@latest
    - cd src/github.com/maxpeal/obinex

build:
    script:
        - go build github.com/maxpeal/obinex/...

test:
    script:
        - go test github.com/maxpeal/obinex/obinex
        - go test github.com/maxpeal/obinex/obinex-watcher
        - go test github.com/maxpeal/obinex/obinex-server
        - go test github.com/maxpeal/obinex/obinex-hwmock

coverage:
    script:
        - ./coverage.sh
        - mv coverage_*.html ../../../../obinex/
    artifacts:
        paths:
            - coverage_obinex-server.html
